version: "3.9"

services:
  app:
    build: .
    container_name: crm_app
    restart: always
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev   # 👈 use nodemon in dev
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: crm_mysql
    restart: always
    ports:
      - "8082:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-crm_db}
      MYSQL_USER: ${MYSQL_USER:-crm_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
